### ISSUE TITLE
Does not work without CSS modules

### ISSUE THREAD

**Issue by torkelrogstad** [Ergosign/storybook-addon-pseudo-states#10]
**Describe the bug**
I cannot get this addon to work without using CSS modules. 

**To Reproduce**
1. Clone my fork of this repo: https://github.com/torkelrogstad/create-react-app-storybook-addon-pseuo-states
2. install deps: `yarn`
3. start storybook: `yarn storybook`
4. Observe that pseudoelements aren't applied

**Expected behavior**
I'd expect pseudoelements to apply

Any help on getting this to work without CSS modules would be much appreciated.

**Comment by philippone** [comment]
Hello @torkelrogstad ,

thanks for your issue. 

It's fixed in latest release [`v0.0.1-alpha.30`](https://github.com/Ergosign/storybook-addon-pseudo-states/releases/tag/v0.0.1-alpha.30).

I added your example to [my example repo](https://github.com/philippone/create-react-app-storybook-addon-pseuo-states/tree/master/src/SimpleButtonWithoutCssModules). Here you can see the running [demo](https://philippone.github.io/create-react-app-storybook-addon-pseuo-states/?path=/story/button--simple-button-without-css-modules).

**Comment by torkelrogstad** [comment]
Thanks a lot for looking into this. Works perfectly now!
