### ISSUE TITLE
How to get pseudo state classes on DOM element

### ISSUE THREAD

**Issue by anushreepatil** [Ergosign/storybook-addon-pseudo-states#36]
Hi,

Thank you for this addon. This is exactly what I need to display all button states from our application.  I am having trouble getting pseudo-classes applied to my DOM button element. We are using the `react-bootstrap` library `button` with classes (btn-primary, btn-secondary, etc.). Our CSS is not where our storybook stories are. It is being linked to stories from our in-house CSS library. 

![image](https://user-images.githubusercontent.com/9013879/101428813-59feb480-38b6-11eb-866a-7c48fd6d51f1.png)

![image](https://user-images.githubusercontent.com/9013879/101428487-a990b080-38b5-11eb-874e-9c60fba9d8bb.png)

This is how the DOM looks. The demo CRA app is working fine locally. I am not sure what is missing. What code takes care of adding the pseudo-classes to DOM elements? I am not concerned at this point about applying class styles; just getting the pseudo-classes would help. Thank you!

**Comment by philippone** [comment]
Hello @anushreepatil ,

it's strange that the pseudo-classes are not applied to your DOM because that should always be attached to the host element of your story (or the specified `paramerters.selector` element).

Do you have any `selector` specified?
```
decorators: [withPseudo],
  parameters: {
    withPseudo: { selector: 'button' },
  },
```

You can find the code adding the pseudo-classes here: https://github.com/Ergosign/storybook-addon-pseudo-states/blob/master/src/react/react.tsx#L153

Are there any console logs that could help? You could set breakpoints in the browser to the (transpiled) file above and try to trace the error.

I took a quick look at `react-bootstrap` and I guess there is a problem how the component itself applies its `variant`s.

(1) The react usage of a button:

```html
<Button variant="secondary">Secondary</Button>{' '}
```

(2) Renders to:

```html
<button type="button" class="btn btn-outline-secondary">Secondary</button>
```

The classes (`btn btn-outline-secondary`) are added to the DOM during the mounting step of the component and I guess the add-on steps in to early, i.e. the add-on sees (1) add the pseudo-class and then the component itself overwrites the `classlist` and removes the pseudo-classes again. We need to find a way to wait until (2) is rendered and then apply the pseudo-classes.

**Comment by anushreepatil** [comment]
Thank you, @philippone! 
I tried with `selector,` but that didn't work either. 
I tried using `react-bootstrap-button`  in the CRA demo code directly, and it is working there. So, I am guessing it might be on our side. The way we use `presets` and `loaders`?! Thank you for pointing out the code used to add pseudo-states. I will try to debug to see if I get any clue.
In the meantime, I am writing the pseudo-states on elements and in my CSS explicitly. Thank you for the concept!

**Comment by philippone** [comment]
Hi @anushreepatil ,

> The way we use presets and loaders?

I guess the preset and loaders are not part of this problem because in your screenshot of your first post the pseudo-class is missing in the `classlist` of `button`. Preset is only responsible to create styling classes automatically.

For instance `.hover` is missing:
```html
<button type="button" class="Button btn btn-default">Button</button>
```

```html
<button type="button" class="Button btn btn-default .hover">Button</button>
```

Maybe you could provide an example repo, then I can test it, too.
